os: linux
jobs:
  include:
    - language: python
      python: 3.7
      install:
        - pip install pipenv
        - pipenv install
      script: docs/build_docs.sh

notifications:
  irc:
    channels:
      - "ircs://chat.freenode.net:6697/##jwf"
      - "ircs://chat.freenode.net:5597/#rit-librecorps"
    template:
      - "[%{repository_name}:%{branch}@%{commit} - build #%{build_number}] CI %{result}! (%{build_url})"
    on_success: change
    on_failure: always
